### ISSUE TITLE
Mise à jour du bandeau Cookie

### ISSUE THREAD

**Issue by OMoukoko** [SocialGouv/ozensemble-site#10]
Bonjour l'équipe

Nous vous rappelons que de nouvelles recommandations relatives aux cookies de la CNIL nécessitent une mise à jour du bandeau cookie du site Ozensemble.

Vous trouverez sur le nextcloud de la Fabrique des recommandations qui rappellent l'ensemble des informations à insérer dans le bandeau cookie et les modalités d'affichage et qui ne sont pas présentes à ce jour. Les mentions existantes dans la politique de gestion de cookies ne peut constituer qu'un premier degré d'information.
<img width="1250" alt="Capture d’écran 2021-02-18 à 16 26 04" src="https://user-images.githubusercontent.com/79263610/108379393-28835d00-7206-11eb-91f3-fba5d064df55.png">
<img width="1278" alt="Capture d’écran 2021-02-18 à 16 26 20" src="https://user-images.githubusercontent.com/79263610/108379410-2de0a780-7206-11eb-91b0-51561e5ac5e7.png">

Nous rappelons que le bandeau doit être affiché dès le début de la navigation (et non après scrollage) et qu'il convient d'attendre impérativement le consentement des personnes pour déposer les cookies (sauf ceux exemptés de consentement, ce qui n'est le cas pour aucun des cookies présent sur le site 👍 
<img width="1289" alt="Capture d’écran 2021-02-18 à 16 19 03" src="https://user-images.githubusercontent.com/79263610/108378983-c3c80280-7205-11eb-87b8-cd15d5a7506a.png">

A votre disposition, pour des renseignements si vous le souhaitez,

Très cordialement,

Osiris Moukoko,
NumériCité

**Comment by OMoukoko** [comment]
La mention telle qu'elle existe n'est également pas conforme car vous ne pouvez "supposer l'acceptation de l'utilisation des cookies".

**Comment by revolunet** [comment]
Bonjour @OMoukoko, merci pour le report, peux-tu stp vérifier que la version sur cette adresse est conforme ? https://ozensemble.fabrique.social.gouv.fr

Il n'y a pas de cookie excepté celui du Matomo de la Fabrique qui est configuré globalement pour anonymiser les données, donc a priori le bandeau ne serait pas nécessaire ?

**Comment by OMoukoko** [comment]
Bonjour @revolunet , 
parfait pas de Cookies de mon côté. 

Merci.
